version: '2'
services:
    jhipsteronlinesample-app:
        image: jhipsteronlinesample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsteronlinesample-mysql:3306/jhipsteronlinesample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsteronlinesample-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsteronlinesample-mysql:
        extends:
            file: mysql.yml
            service: jhipsteronlinesample-mysql
    jhipsteronlinesample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsteronlinesample-elasticsearch
